### PR TITLE
Formatted project using cargo fmt

### PR DESCRIPTION
**Pull request by skytz**

### CODE REVIEW

**Comment by kurtbuilds** [comment]
I appreciate this contribution, but I'm going to decline it.

Today, I code in IntelliJ and use its formatter. I'm open to rustfmt, so after getting your PR, I tried playing with it for ormlite & other projects.

All of the following is personal opinion: Right now, rustfmt configuration & features are in a state where I find it quite frustrating to use. The defaults are way too aggressive with indentation and line wrapping. I wasn't able to easily (or not easily) find configuration options to resolve my pain points. Moreover, I think it makes a number of non-configurable choices that I think are unquestionably worse. I opened an issue about one in particular where's rustfmt causes almost identical to format fairly differently (https://github.com/rust-lang/rustfmt/issues/5783) and in that interaction the team seemed unwilling to engage in the substance of the issue I filed.

Often, rustfmt does a good job of formatting, but for now, I think manual formatting is still superior, and there aren't so many contributors where formatting inconsistency is impacting the project.

I'm open to smaller scoped PRs, PRs where rustfmt is only run on code you're already touching, or the addition of a `.rustfmt.toml` file with:

```
ignore = ["/"]
```

if you have default editor settings that otherwise prevent you from contributing to the project. (Note that `ignore` is still unstable.)

**Comment by skytz** [comment]
I googled for a bit and i couldn't find the rules IntelliJ uses for its rust formatter.
I will stop my formatter and reverse all the formatting issues manually, although i would suggest adding some sort of formatting doc yourself, something you are happy with.
Rustfmt does an ok job, and if you dont like something in particular, you can disable that rule in the `rustfmt.toml` or use `#[rustfmt::skip]`.

I personally preffer clippy

**Comment by skytz** [comment]
I understand your point, and i will format the project manually on the code i wrote.

My take on the formatting issue is simple: 
Consistent formatting (even if it looks bad in some cases) is better than manually formatting, especially when working in a team (or in this case open source).
Mostly because i can check if the formatting is the same across team members.
Combining it with clippy, i'm resonably sure everyone's code looks kinda the same.

If your issue is that in some cases, like the example you gave in the rustfmt issue, rustfmt doesn't do what you want, `#[rustfmt::skip]` should fix the problem.
If its a general thing ... 🤷‍♂️.

This problem won't dissapear if other people want to contribute to the package, and some formatting rules would help reduce friction and overhead.

**Comment by kurtbuilds** [comment]
Definitely. It's something I'd revisit when the rustfmt gets more configuration/development/love and/or this project has many more contributors to make consistency that much more important.

**Pull request closed without merging**
