### PR TITLE
Tweaks and update

### PR DESCRIPTION
**Pull request by franklx**
This PR contains 4 _changes_:
1.`impl Serialize for Join` to flatten the Join struct in Json serialization via serde;
2. Add constraints to `IdType` (so we can use `_id()` as `HashMap` key);
3. Changes required for upgrading from `syn@1` to `syn@2`;
4. Update all dependencies to latest version (including `sqlx` 0.7);
I can split this PR if you prefer to not to merge all.
You can ever reject the PR completely :)

### CODE REVIEW

**Comment by kurtbuilds** [comment]
Thank you! I'll look over this, but on first skim, it looks good. I appreciate the updates to syn and sqlx - been meaning to get around to those!

**Comment by franklx** [comment]
Very good.
For the `cli` to work the same sqlx@0.7 update is needed for [sqlmo](https://github.com/kurtbuilds/sqlmo/compare/master...franklx:sqlmo:master) (I didn't open a PR for this).
I evaluated _any_ other rust ORM and ORM-like library out there and I found `ormlite` "hybrid" approach the best one.
I'm even working on other implementations for `ormlite`:
1. A one-to-many implementation based on macros and [indexmap](https://github.com/bluss/indexmap) that's quite simple but is working very well;
2. A (WIP) struct `Model` generator (a very simple `sea generate`) for `postgresql` (for now);

if you are interested in any of those I can share the code.

**Comment by kurtbuilds** [comment]
Great!

I haven't seen `sea generate`, but curious to see what that looks like when it's ready to share.

Definitely welcome a one-to-many PR too. Though that definitely should be it's own PR

**Comment by kurtbuilds** [comment]
I released 0.15 of sqlmo using sqlx 0.7.

**Comment by kurtbuilds** [comment]
Ok, gave this a more thorough review, looks great. I'll merge shortly.

I'll revert the `path = ` configuration for sqlmo.

FYI, you can put overrides for those values in `.cargo/config.toml` file, which can be `.gitignore`-ed.

```
$ pwd
/Users/kurt/work/ormlite
$ cat .cargo/config.toml
[patch.crates-io]
sqlmo = { path = "../sqlmo" }
```

**Comment by franklx** [comment]
I didn't know about .cargo/config.toml, thank you very much!

**Pull request merged**
